export const LOUNGE_STATUS_REQUEST = 'LOUNGE_STATUS_REQUEST';
export const LOUNGE_STATUS_POLL_START = 'LOUNGE_STATUS_POLL_START';
export const LOUNGE_STATUS_POLL_STOP = 'LOUNGE_STATUS_POLL_STOP';
export const LOUNGE_STATUS_SUCCESS = 'LOUNGE_STATUS_SUCCESS';
export const LOUNGE_STATUS_FAILURE = 'LOUNGE_STATUS_FAILURE';
